export const TEMPLATE_CATEGORIES = ['All', 'Traditional', 'Modern', 'Minimal', 'Elegant'];

export const TEMPLATES_CATALOG = [
  {
    id: 'trad-classic-01',
    name: 'Traditional Classic',
    category: 'Traditional',
    badge: 'Popular',
    thumbnailColor: '#FFF8EE',
    headerColor: '#8B0000',
    accentColor: '#D4AF37',
    headline: 'Find Your Life Partner',
    subHeadline: 'Ornate floral & cultural layout',
    previewImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&q=80&w=400',
    description: 'Gold-accented floral borders tailored for matrimony and family biodata',
    recommendedFor: ['matrimony', 'family'],
    rating: '4.9 ★ (2.4k)',
    isPro: false,
  },
  {
    id: 'elegant-modern-02',
    name: 'Elegant Modern',
    category: 'Modern',
    badge: 'Pro',
    thumbnailColor: '#F0F4FF',
    headerColor: '#6C5CE7',
    accentColor: '#A29BFE',
    headline: 'Together for Tomorrow',
    subHeadline: 'Sleek executive dual-column',
    previewImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    description: 'Crisp corporate aesthetic for senior professionals and tech leaders',
    recommendedFor: ['professional', 'freelancer'],
    rating: '4.8 ★ (1.8k)',
    isPro: true,
  },
  {
    id: 'royal-theme-03',
    name: 'Royal Theme',
    category: 'Traditional',
    badge: 'Royal',
    thumbnailColor: '#FFF0F2',
    headerColor: '#C0392B',
    accentColor: '#F39C12',
    headline: 'A New Journey Together',
    subHeadline: 'Sunset luxury gold foil style',
    previewImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=400',
    description: 'High-end royal presentation with ornate crests and family lineage tree',
    recommendedFor: ['matrimony', 'portfolio'],
    rating: '5.0 ★ (950)',
    isPro: true,
  },
  {
    id: 'minimal-clean-04',
    name: 'Minimal Clean',
    category: 'Minimal',
    badge: 'Trending',
    thumbnailColor: '#F4FBF7',
    headerColor: '#2D3436',
    accentColor: '#10B981',
    headline: 'Simple. Beautiful. Real.',
    subHeadline: 'Botanical foliage & spacious typography',
    previewImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    description: 'Airy layout with subtle green botanicals for designers and creators',
    recommendedFor: ['student', 'freelancer', 'portfolio'],
    rating: '4.9 ★ (3.1k)',
    isPro: false,
  },
  {
    id: 'professional-resume-05',
    name: 'Modern Executive',
    category: 'Modern',
    badge: 'Career',
    thumbnailColor: '#EFF6FF',
    headerColor: '#1E40AF',
    accentColor: '#3B82F6',
    headline: 'Senior Tech Lead & Builder',
    subHeadline: 'Clean ATS-friendly resume format',
    previewImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    description: 'Structured resume profile with skills cloud, project highlights and metrics',
    recommendedFor: ['professional', 'student'],
    rating: '4.8 ★ (1.5k)',
    isPro: false,
  },
  {
    id: 'creative-portfolio-06',
    name: 'Creative Studio',
    category: 'Minimal',
    badge: 'Design',
    thumbnailColor: '#FFF7ED',
    headerColor: '#D97706',
    accentColor: '#F59E0B',
    headline: 'Art Direction & Visuals',
    subHeadline: 'Bold gallery aesthetic',
    previewImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    description: 'Striking creative profile for artists, photographers and UX writers',
    recommendedFor: ['freelancer', 'portfolio'],
    rating: '4.9 ★ (880)',
    isPro: true,
  },
];
